[package]
name = "waka"
version = "0.1.0"
edition = "2024"

description = "A front-end for libalpm, inspired by nala"
license = "GPL-3.0-only"
authors = ["Shisones"]

[dependencies]
clap = { version = "4", features = ["derive"] }
alpm = "5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
termsize = "0.1"
ctrlc = "3"
unicode-width = "0.2"
tempfile = "3"

[profile.release]
lto = true
codegen-units = 1
strip = true
